name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
permissions:
  contents: write
jobs:
  study-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.event_name:${{ github.event_name }},runner.os:${{ runner.os }},${{ github.ref }},${{ github.repository }}"
      - run: echo `pwd` `hostname`
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      - run: |
            php -v
            php -m
      - name: 生成文件
        run: php -r " file_put_contents('1.txt',date('Y-m-d H:i:s'));"
      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          branch: gh-pages
          folder: .
  job2:
    runs-on: windows-latest
    steps:
      - run: node --version


